import React, { useState, useMemo } from "react";
import {
  Box,
  Typography,
  Button,
  TextField,
  IconButton,
  Paper,
  Collapse,
  Chip,
  Switch,
  FormControlLabel,
  Tooltip,
  FormControl,
  InputLabel,
  Select,
  MenuItem,
  Checkbox,
  Dialog,
  DialogTitle,
  DialogContent,
  DialogActions,
  RadioGroup,
  Radio,
  FormLabel,
  CircularProgress,
} from "@mui/material";
import { notification } from "../../services/notificationService";
import AddIcon from "@mui/icons-material/Add";
import DeleteIcon from "@mui/icons-material/Delete";
import ContentCopyIcon from "@mui/icons-material/ContentCopy";
import ExpandMoreIcon from "@mui/icons-material/ExpandMore";
import ExpandLessIcon from "@mui/icons-material/ExpandLess";
import { useDispatch } from "react-redux";
import { AppDispatch } from "../../Redux Toolkit/Store";
import {
  addVariant,
  updateVariant,
  removeVariant,
  bulkUpdateVariantPricing,
  bulkUpdateVariantInventory,
  bulkUpdateVariantStatus,
} from "../../Redux Toolkit/Seller/sellerProductSlice";
import {
  Product,
  ProductVariant,
  ProductImage,
  AttributeDefinition,
  DynamicAttribute,
} from "../../types/productTypes";
import ProductImageUpload from "./ProductImageUpload";

interface VariantManagerProps {
  product: Product;
  jwt: string | null;
}

const createEmptyVariant = (
  supportedAttrs: AttributeDefinition[]
): Omit<ProductVariant, "id"> => ({
  sku: "",
  attributes: {
    color: "",
    size: "",
    storage: "",
    ram: "",
    custom: [],
    dynamic: supportedAttrs
      .filter((a) => a.active !== false && a.variantAttribute)
      .map((a) => ({ name: a.code, value: "" })),
  },
  price: 0,
  mrpPrice: 0,
  discountPercent: 0,
  quantity: 0,
  images: [],
  weight: undefined,
  isActive: true,
});

const VariantManager: React.FC<VariantManagerProps> = ({ product, jwt }) => {
  const dispatch = useDispatch<AppDispatch>();
  const [expandedId, setExpandedId] = useState<string | null>(null);
  const [addingNew, setAddingNew] = useState(false);
  const [customAttrKey, setCustomAttrKey] = useState("");
  const [customAttrValue, setCustomAttrValue] = useState("");

  const [selectedIds, setSelectedIds] = useState<Set<string>>(new Set());
  const [bulkPriceDialogOpen, setBulkPriceDialogOpen] = useState(false);
  const [bulkStockDialogOpen, setBulkStockDialogOpen] = useState(false);
  const [bulkStatusDialogOpen, setBulkStatusDialogOpen] = useState(false);
  const [bulkLoading, setBulkLoading] = useState(false);

  const [bulkPrices, setBulkPrices] = useState<{ price: number | string; mrpPrice: number | string }>({ price: "", mrpPrice: "" });
  const [bulkStock, setBulkStock] = useState<{ operation: "set" | "increment" | "decrement"; quantity: number | string }>({ operation: "set", quantity: "" });
  const [bulkStatus, setBulkStatus] = useState<{ isActive: boolean }>({ isActive: true });

  const variants = product.variants || [];

  const supportedAttributes: AttributeDefinition[] = useMemo(() => {
    const attrs = product.category?.supportedAttributes || [];
    return attrs.filter((a) => a.active !== false);
  }, [product.category]);

  const variantAttrs: AttributeDefinition[] = useMemo(
    () => supportedAttributes.filter((a) => a.variantAttribute),
    [supportedAttributes]
  );

  const hasDynamicSystem = variantAttrs.length > 0;

  const [newVariant, setNewVariant] = useState(() =>
    createEmptyVariant(variantAttrs)
  );

  const toggleExpand = (variantId: string) => {
    setExpandedId(expandedId === variantId ? null : variantId);
  };

  const handleAddVariant = async () => {
    if (newVariant.price <= 0) {
      notification.error("Price must be greater than 0");
      return;
    }

    try {
      // SKU is auto-generated by the backend — do not send it
      const { sku: _sku, ...variantDataWithoutSku } = newVariant;
      await dispatch(
        addVariant({
          productId: product.id!,
          variantData: variantDataWithoutSku,
          jwt,
        })
      ).unwrap();
      notification.success("Variant added successfully");
      setNewVariant(createEmptyVariant(variantAttrs));
      setAddingNew(false);
    } catch (err: any) {
      notification.error(err?.message || "Failed to add variant");
    }
  };

  const handleUpdateVariant = async (
    variantId: string,
    updateData: Partial<ProductVariant>
  ) => {
    try {
      await dispatch(
        updateVariant({
          productId: product.id!,
          variantId,
          updateData,
          jwt,
        })
      ).unwrap();
      notification.success("Variant updated");
    } catch (err: any) {
      notification.error(err?.message || "Failed to update variant");
    }
  };

  const handleRemoveVariant = async (variantId: string) => {
    if (!window.confirm("Remove this variant? This cannot be undone.")) return;
    try {
      await dispatch(
        removeVariant({
          productId: product.id!,
          variantId,
          jwt,
        })
      ).unwrap();
      notification.success("Variant removed");
      if (expandedId === variantId) setExpandedId(null);
    } catch (err: any) {
      notification.error(err?.message || "Failed to remove variant");
    }
  };

  const handleDuplicateVariant = (variant: ProductVariant) => {
    const { id: _id, ...rest } = variant;
    setNewVariant({
      ...rest,
      sku: "",
    });
    setAddingNew(true);
  };

  const toggleSelect = (variantId: string) => {
    setSelectedIds((prev) => {
      const next = new Set(prev);
      if (next.has(variantId)) next.delete(variantId);
      else next.add(variantId);
      return next;
    });
  };

  const toggleSelectAll = () => {
    if (selectedIds.size === variants.length && variants.length > 0) {
      setSelectedIds(new Set());
    } else {
      setSelectedIds(new Set(variants.filter((v) => v.id).map((v) => v.id!)));
    }
  };

  const handleBulkPriceUpdate = async () => {
    if (selectedIds.size === 0) return;
    setBulkLoading(true);
    try {
      const priceData: any = {};
      if (bulkPrices.price !== "") priceData.price = Number(bulkPrices.price);
      if (bulkPrices.mrpPrice !== "") priceData.mrpPrice = Number(bulkPrices.mrpPrice);
      await dispatch(
        bulkUpdateVariantPricing({
          productId: product.id!,
          variantIds: Array.from(selectedIds),
          priceData,
          jwt,
        })
      ).unwrap();
      notification.success(`Updated pricing for ${selectedIds.size} variant(s)`);
      setSelectedIds(new Set());
      setBulkPriceDialogOpen(false);
      setBulkPrices({ price: "", mrpPrice: "" });
    } catch (err: any) {
      notification.error(err?.message || "Bulk price update failed");
    } finally {
      setBulkLoading(false);
    }
  };

  const handleBulkStockUpdate = async () => {
    if (selectedIds.size === 0) return;
    setBulkLoading(true);
    try {
      await dispatch(
        bulkUpdateVariantInventory({
          productId: product.id!,
          variantIds: Array.from(selectedIds),
          operation: bulkStock.operation,
          quantity: Number(bulkStock.quantity),
          jwt,
        })
      ).unwrap();
      notification.success(`Updated stock for ${selectedIds.size} variant(s)`);
      setSelectedIds(new Set());
      setBulkStockDialogOpen(false);
      setBulkStock({ operation: "set", quantity: "" });
    } catch (err: any) {
      notification.error(err?.message || "Bulk stock update failed");
    } finally {
      setBulkLoading(false);
    }
  };

  const handleBulkStatusUpdate = async () => {
    if (selectedIds.size === 0) return;
    setBulkLoading(true);
    try {
      await dispatch(
        bulkUpdateVariantStatus({
          productId: product.id!,
          variantIds: Array.from(selectedIds),
          isActive: bulkStatus.isActive,
          jwt,
        })
      ).unwrap();
      notification.success(`Updated status for ${selectedIds.size} variant(s)`);
      setSelectedIds(new Set());
      setBulkStatusDialogOpen(false);
    } catch (err: any) {
      notification.error(err?.message || "Bulk status update failed");
    } finally {
      setBulkLoading(false);
    }
  };

  const handleAddCustomAttribute = () => {
    if (!customAttrKey.trim() || !customAttrValue.trim()) return;
    setNewVariant({
      ...newVariant,
      attributes: {
        ...newVariant.attributes,
        custom: [
          ...(newVariant.attributes.custom || []),
          { key: customAttrKey.trim(), value: customAttrValue.trim() },
        ],
      },
    });
    setCustomAttrKey("");
    setCustomAttrValue("");
  };

  const getVariantLabel = (variant: ProductVariant) => {
    const parts: string[] = [];
    if (hasDynamicSystem) {
      const dynamic = variant.attributes.dynamic || [];
      dynamic.forEach((d) => {
        if (d.value) parts.push(d.value);
      });
    } else {
      if (variant.attributes.color) parts.push(variant.attributes.color);
      if (variant.attributes.size) parts.push(variant.attributes.size);
      if (variant.attributes.storage) parts.push(variant.attributes.storage);
      if (variant.attributes.ram) parts.push(variant.attributes.ram);
    }
    if (variant.attributes.custom?.length) {
      variant.attributes.custom.forEach((c) =>
        parts.push(`${c.key}: ${c.value}`)
      );
    }
    return parts.length > 0 ? parts.join(" / ") : "Default Variant";
  };

  const updateDynamicAttr = (
    attrs: DynamicAttribute[],
    attrName: string,
    value: string
  ): DynamicAttribute[] => {
    const existing = attrs.find((a) => a.name === attrName);
    if (existing) {
      return attrs.map((a) => (a.name === attrName ? { ...a, value } : a));
    }
    return [...attrs, { name: attrName, value }];
  };

  const renderDynamicAttributeInput = (
    attr: AttributeDefinition,
    currentValue: string,
    onChange: (value: string) => void
  ) => {
    if (attr.type === "select" && attr.options && attr.options.length > 0) {
      return (
        <FormControl key={attr.code} size="small" sx={{ minWidth: 150 }}>
          <InputLabel>{attr.name}</InputLabel>
          <Select
            label={attr.name}
            value={currentValue}
            onChange={(e) => onChange(e.target.value)}
          >
            <MenuItem value="">
              <em>None</em>
            </MenuItem>
            {attr.options.map((opt) => (
              <MenuItem key={opt} value={opt}>
                {opt}
              </MenuItem>
            ))}
          </Select>
        </FormControl>
      );
    }

    if (attr.type === "boolean") {
      return (
        <FormControlLabel
          key={attr.code}
          control={
            <Switch
              checked={currentValue === "true"}
              onChange={(e) =>
                onChange(e.target.checked ? "true" : "false")
              }
            />
          }
          label={attr.name}
        />
      );
    }

    return (
      <TextField
        key={attr.code}
        size="small"
        label={attr.name}
        type={attr.type === "number" ? "number" : "text"}
        value={currentValue}
        onChange={(e) => onChange(e.target.value)}
        required={attr.required}
      />
    );
  };

  return (
    <Box className="space-y-4">
      <Typography variant="h6" fontWeight="bold">
        Product Variants ({variants.length})
      </Typography>

      {variants.length > 0 && (
        <Box className="flex items-center gap-2">
          <Checkbox
            checked={selectedIds.size === variants.length && variants.length > 0}
            indeterminate={selectedIds.size > 0 && selectedIds.size < variants.length}
            onChange={toggleSelectAll}
          />
          <Typography variant="body2">
            {selectedIds.size === 0
              ? "Select all variants"
              : `${selectedIds.size} of ${variants.length} selected`}
          </Typography>
        </Box>
      )}

      {selectedIds.size > 0 && (
        <Paper variant="outlined" sx={{ p: 1.5, display: "flex", gap: 1, alignItems: "center" }}>
          <Typography variant="body2" fontWeight="bold" sx={{ mr: 1 }}>
            Bulk Actions ({selectedIds.size} selected):
          </Typography>
          <Button size="small" variant="contained" onClick={() => setBulkPriceDialogOpen(true)}>
            Update Pricing
          </Button>
          <Button size="small" variant="contained" color="secondary" onClick={() => setBulkStockDialogOpen(true)}>
            Update Stock
          </Button>
          <Button size="small" variant="contained" color={bulkStatus.isActive ? "warning" : "success"} onClick={() => setBulkStatusDialogOpen(true)}>
            Update Status
          </Button>
        </Paper>
      )}

      {/* Existing Variants */}
      {variants.map((variant) => (
        <Paper
          key={variant.id}
          variant="outlined"
          sx={{ p: 2, opacity: variant.isActive ? 1 : 0.6 }}
        >
          {/* Variant Header Row */}
          <Box className="flex items-center justify-between gap-2">
            <Box className="flex items-center gap-2 flex-1 min-w-0">
              <Checkbox
                size="small"
                checked={variant.id ? selectedIds.has(variant.id) : false}
                onChange={() => variant.id && toggleSelect(variant.id)}
                onClick={(e) => e.stopPropagation()}
              />
              <IconButton
                size="small"
                onClick={() => variant.id && toggleExpand(variant.id)}
                aria-label={`Expand variant ${getVariantLabel(variant)}`}
              >
                {expandedId === variant.id ? (
                  <ExpandLessIcon />
                ) : (
                  <ExpandMoreIcon />
                )}
              </IconButton>
              <Typography
                variant="body2"
                fontWeight="bold"
                className="truncate"
              >
                {getVariantLabel(variant)}
              </Typography>
              <Chip
                size="small"
                label={variant.sku}
                variant="outlined"
                sx={{ fontSize: "0.7rem" }}
              />
              {!variant.isActive && (
                <Chip
                  size="small"
                  label="Inactive"
                  color="default"
                  sx={{ fontSize: "0.7rem" }}
                />
              )}
            </Box>
            <Box className="flex items-center gap-1">
              <Typography
                variant="caption"
                className="font-semibold whitespace-nowrap"
              >
                ₹{variant.price} | Stock: {variant.quantity}
              </Typography>
              <Tooltip title="Duplicate variant">
                <IconButton
                  size="small"
                  onClick={() => handleDuplicateVariant(variant)}
                  aria-label={`Duplicate variant ${getVariantLabel(variant)}`}
                >
                  <ContentCopyIcon fontSize="small" />
                </IconButton>
              </Tooltip>
              <Tooltip title="Remove variant">
                <IconButton
                  size="small"
                  color="error"
                  onClick={() => variant.id && handleRemoveVariant(variant.id)}
                  aria-label={`Remove variant ${getVariantLabel(variant)}`}
                >
                  <DeleteIcon fontSize="small" />
                </IconButton>
              </Tooltip>
            </Box>
          </Box>

          {/* Expanded Detail Panel */}
          {variant.id && (
            <Collapse in={expandedId === variant.id}>
              <Box className="mt-3 space-y-3 border-t pt-3">
                {/* SKU — Read Only */}
                <TextField
                  fullWidth
                  size="small"
                  label="SKU (Auto-generated)"
                  value={variant.sku}
                  disabled
                  InputProps={{ readOnly: true }}
                  helperText="SKU cannot be changed after creation"
                />

                {/* Attributes — Dynamic or Legacy */}
                <Box className="flex flex-wrap gap-2" alignItems="center">
                  {hasDynamicSystem
                    ? variantAttrs.map((attr) => {
                        const dynamic =
                          variant.attributes.dynamic || [];
                        const current = dynamic.find(
                          (d) => d.name === attr.code
                        );
                        return renderDynamicAttributeInput(
                          attr,
                          current?.value || "",
                          (val) =>
                            handleUpdateVariant(variant.id!, {
                              attributes: {
                                ...variant.attributes,
                                dynamic: updateDynamicAttr(
                                  dynamic,
                                  attr.code,
                                  val
                                ),
                              },
                            })
                        );
                      })
                    : <>
                        <TextField
                          size="small"
                          label="Color"
                          value={variant.attributes.color || ""}
                          onChange={(e) =>
                            handleUpdateVariant(variant.id!, {
                              attributes: {
                                ...variant.attributes,
                                color: e.target.value,
                              },
                            })
                          }
                        />
                        <TextField
                          size="small"
                          label="Size"
                          value={variant.attributes.size || ""}
                          onChange={(e) =>
                            handleUpdateVariant(variant.id!, {
                              attributes: {
                                ...variant.attributes,
                                size: e.target.value,
                              },
                            })
                          }
                        />
                        <TextField
                          size="small"
                          label="Storage"
                          value={variant.attributes.storage || ""}
                          onChange={(e) =>
                            handleUpdateVariant(variant.id!, {
                              attributes: {
                                ...variant.attributes,
                                storage: e.target.value,
                              },
                            })
                          }
                        />
                        <TextField
                          size="small"
                          label="RAM"
                          value={variant.attributes.ram || ""}
                          onChange={(e) =>
                            handleUpdateVariant(variant.id!, {
                              attributes: {
                                ...variant.attributes,
                                ram: e.target.value,
                              },
                            })
                          }
                        />
                      </>
                  }
                  <TextField
                    size="small"
                    label="Weight (g)"
                    type="number"
                    value={variant.weight || ""}
                    onChange={(e) =>
                      handleUpdateVariant(variant.id!, {
                        weight: e.target.value
                          ? Number(e.target.value)
                          : undefined,
                      })
                    }
                  />
                </Box>

                {/* Custom Attributes Display */}
                {variant.attributes.custom &&
                  variant.attributes.custom.length > 0 && (
                    <Box className="flex flex-wrap gap-1">
                      {variant.attributes.custom.map((attr, idx) => (
                        <Chip
                          key={idx}
                          size="small"
                          label={`${attr.key}: ${attr.value}`}
                          onDelete={() => {
                            const updatedCustom =
                              variant.attributes.custom!.filter(
                                (_, i) => i !== idx
                              );
                            handleUpdateVariant(variant.id!, {
                              attributes: {
                                ...variant.attributes,
                                custom: updatedCustom,
                              },
                            });
                          }}
                        />
                      ))}
                    </Box>
                  )}

                {/* Pricing */}
                <Box className="flex flex-wrap gap-2">
                  <TextField
                    size="small"
                    label="MRP Price"
                    type="number"
                    value={variant.mrpPrice}
                    onChange={(e) =>
                      handleUpdateVariant(variant.id!, {
                        mrpPrice: Number(e.target.value),
                      })
                    }
                  />
                  <TextField
                    size="small"
                    label="Selling Price"
                    type="number"
                    value={variant.price}
                    onChange={(e) =>
                      handleUpdateVariant(variant.id!, {
                        price: Number(e.target.value),
                      })
                    }
                  />
                  <TextField
                    size="small"
                    label="Stock"
                    type="number"
                    value={variant.quantity}
                    onChange={(e) =>
                      handleUpdateVariant(variant.id!, {
                        quantity: Number(e.target.value),
                      })
                    }
                  />
                </Box>

                {/* Active Toggle */}
                <FormControlLabel
                  control={
                    <Switch
                      checked={variant.isActive}
                      onChange={(e) =>
                        handleUpdateVariant(variant.id!, {
                          isActive: e.target.checked,
                        })
                      }
                    />
                  }
                  label="Active"
                />

                {/* Variant Images */}
                <Box>
                  <Typography
                    variant="caption"
                    fontWeight="bold"
                    display="block"
                    mb={1}
                  >
                    Variant Images (optional)
                  </Typography>
                  <ProductImageUpload
                    images={variant.images || []}
                    onChange={(images: ProductImage[]) =>
                      handleUpdateVariant(variant.id!, { images })
                    }
                  />
                </Box>
              </Box>
            </Collapse>
          )}
        </Paper>
      ))}

      {/* Add New Variant */}
      {addingNew ? (
        <Paper variant="outlined" sx={{ p: 2 }} className="space-y-3">
          <Typography variant="subtitle2" fontWeight="bold">
            New Variant
          </Typography>
          <Box className="flex flex-wrap gap-2" alignItems="center">
            <TextField
              size="small"
              label="SKU"
              value="Auto-generated on save"
              disabled
              sx={{ minWidth: 180 }}
              helperText="SKU is generated automatically from category and attributes"
            />
            {hasDynamicSystem
              ? variantAttrs.map((attr) => {
                  const dynamic = newVariant.attributes.dynamic || [];
                  const current = dynamic.find((d) => d.name === attr.code);
                  return renderDynamicAttributeInput(
                    attr,
                    current?.value || "",
                    (val) =>
                      setNewVariant({
                        ...newVariant,
                        attributes: {
                          ...newVariant.attributes,
                          dynamic: updateDynamicAttr(dynamic, attr.code, val),
                        },
                      })
                  );
                })
              : <>
                  <TextField
                    size="small"
                    label="Color"
                    value={newVariant.attributes.color || ""}
                    onChange={(e) =>
                      setNewVariant({
                        ...newVariant,
                        attributes: {
                          ...newVariant.attributes,
                          color: e.target.value,
                        },
                      })
                    }
                  />
                  <TextField
                    size="small"
                    label="Size"
                    value={newVariant.attributes.size || ""}
                    onChange={(e) =>
                      setNewVariant({
                        ...newVariant,
                        attributes: {
                          ...newVariant.attributes,
                          size: e.target.value,
                        },
                      })
                    }
                  />
                  <TextField
                    size="small"
                    label="Storage"
                    value={newVariant.attributes.storage || ""}
                    onChange={(e) =>
                      setNewVariant({
                        ...newVariant,
                        attributes: {
                          ...newVariant.attributes,
                          storage: e.target.value,
                        },
                      })
                    }
                  />
                  <TextField
                    size="small"
                    label="RAM"
                    value={newVariant.attributes.ram || ""}
                    onChange={(e) =>
                      setNewVariant({
                        ...newVariant,
                        attributes: {
                          ...newVariant.attributes,
                          ram: e.target.value,
                        },
                      })
                    }
                  />
                </>
            }
          </Box>

          {/* Custom Attributes */}
          <Box className="flex items-center gap-2">
            <TextField
              size="small"
              label="Custom Key"
              value={customAttrKey}
              onChange={(e) => setCustomAttrKey(e.target.value)}
              sx={{ width: 120 }}
            />
            <TextField
              size="small"
              label="Custom Value"
              value={customAttrValue}
              onChange={(e) => setCustomAttrValue(e.target.value)}
              sx={{ width: 120 }}
            />
            <Button
              size="small"
              variant="outlined"
              onClick={handleAddCustomAttribute}
            >
              Add
            </Button>
          </Box>
          {newVariant.attributes.custom &&
            newVariant.attributes.custom.length > 0 && (
              <Box className="flex flex-wrap gap-1">
                {newVariant.attributes.custom.map((attr, idx) => (
                  <Chip
                    key={idx}
                    size="small"
                    label={`${attr.key}: ${attr.value}`}
                    onDelete={() => {
                      const updated = newVariant.attributes.custom!.filter(
                        (_, i) => i !== idx
                      );
                      setNewVariant({
                        ...newVariant,
                        attributes: {
                          ...newVariant.attributes,
                          custom: updated,
                        },
                      });
                    }}
                  />
                ))}
              </Box>
            )}

          {/* Pricing */}
          <Box className="flex flex-wrap gap-2">
            <TextField
              size="small"
              label="MRP Price"
              type="number"
              required
              value={newVariant.mrpPrice || ""}
              onChange={(e) =>
                setNewVariant({
                  ...newVariant,
                  mrpPrice: Number(e.target.value),
                })
              }
            />
            <TextField
              size="small"
              label="Selling Price"
              type="number"
              required
              value={newVariant.price || ""}
              onChange={(e) =>
                setNewVariant({
                  ...newVariant,
                  price: Number(e.target.value),
                })
              }
            />
            <TextField
              size="small"
              label="Stock"
              type="number"
              value={newVariant.quantity || ""}
              onChange={(e) =>
                setNewVariant({
                  ...newVariant,
                  quantity: Number(e.target.value),
                })
              }
            />
            <TextField
              size="small"
              label="Weight (g)"
              type="number"
              value={newVariant.weight || ""}
              onChange={(e) =>
                setNewVariant({
                  ...newVariant,
                  weight: e.target.value
                    ? Number(e.target.value)
                    : undefined,
                })
              }
            />
          </Box>

          {/* Variant Images */}
          <ProductImageUpload
            images={newVariant.images || []}
            onChange={(images: ProductImage[]) =>
              setNewVariant({ ...newVariant, images })
            }
          />

          <Box className="flex gap-2">
            <Button
              variant="contained"
              size="small"
              onClick={handleAddVariant}
            >
              Save Variant
            </Button>
            <Button
              variant="outlined"
              size="small"
              onClick={() => {
                setAddingNew(false);
                setNewVariant(createEmptyVariant(variantAttrs));
              }}
            >
              Cancel
            </Button>
          </Box>
        </Paper>
      ) : (
        <Button
          variant="outlined"
          startIcon={<AddIcon />}
          onClick={() => setAddingNew(true)}
        >
          Add Variant
        </Button>
      )}

      {/* Bulk Price Dialog */}
      <Dialog open={bulkPriceDialogOpen} onClose={() => !bulkLoading && setBulkPriceDialogOpen(false)} maxWidth="xs" fullWidth>
        <DialogTitle>Bulk Update Pricing ({selectedIds.size} variant(s))</DialogTitle>
        <DialogContent className="space-y-3" sx={{ pt: "16px !important" }}>
          <TextField
            fullWidth
            size="small"
            label="New Selling Price (₹)"
            type="number"
            value={bulkPrices.price}
            onChange={(e) => setBulkPrices({ ...bulkPrices, price: e.target.value })}
            helperText="Leave blank to keep current price"
          />
          <TextField
            fullWidth
            size="small"
            label="New MRP Price (₹)"
            type="number"
            value={bulkPrices.mrpPrice}
            onChange={(e) => setBulkPrices({ ...bulkPrices, mrpPrice: e.target.value })}
            helperText="Leave blank to keep current MRP"
          />
        </DialogContent>
        <DialogActions>
          <Button onClick={() => { setBulkPriceDialogOpen(false); setBulkPrices({ price: "", mrpPrice: "" }); }} disabled={bulkLoading}>Cancel</Button>
          <Button
            variant="contained"
            onClick={handleBulkPriceUpdate}
            disabled={bulkLoading || (bulkPrices.price === "" && bulkPrices.mrpPrice === "")}
            startIcon={bulkLoading ? <CircularProgress size={16} /> : undefined}
          >
            {bulkLoading ? "Updating..." : "Apply"}
          </Button>
        </DialogActions>
      </Dialog>

      {/* Bulk Stock Dialog */}
      <Dialog open={bulkStockDialogOpen} onClose={() => !bulkLoading && setBulkStockDialogOpen(false)} maxWidth="xs" fullWidth>
        <DialogTitle>Bulk Update Stock ({selectedIds.size} variant(s))</DialogTitle>
        <DialogContent className="space-y-3" sx={{ pt: "16px !important" }}>
          <FormLabel component="legend">Operation</FormLabel>
          <RadioGroup
            row
            value={bulkStock.operation}
            onChange={(e) => setBulkStock({ ...bulkStock, operation: e.target.value as any })}
          >
            <FormControlLabel value="set" control={<Radio size="small" />} label="Set" />
            <FormControlLabel value="increment" control={<Radio size="small" />} label="Increase" />
            <FormControlLabel value="decrement" control={<Radio size="small" />} label="Decrease" />
          </RadioGroup>
          <TextField
            fullWidth
            size="small"
            label="Quantity"
            type="number"
            value={bulkStock.quantity}
            onChange={(e) => setBulkStock({ ...bulkStock, quantity: e.target.value })}
            inputProps={{ min: 0 }}
          />
        </DialogContent>
        <DialogActions>
          <Button onClick={() => { setBulkStockDialogOpen(false); setBulkStock({ operation: "set", quantity: "" }); }} disabled={bulkLoading}>Cancel</Button>
          <Button
            variant="contained"
            color="secondary"
            onClick={handleBulkStockUpdate}
            disabled={bulkLoading || bulkStock.quantity === "" || Number(bulkStock.quantity) < 0}
            startIcon={bulkLoading ? <CircularProgress size={16} /> : undefined}
          >
            {bulkLoading ? "Updating..." : "Apply"}
          </Button>
        </DialogActions>
      </Dialog>

      {/* Bulk Status Dialog */}
      <Dialog open={bulkStatusDialogOpen} onClose={() => !bulkLoading && setBulkStatusDialogOpen(false)} maxWidth="xs" fullWidth>
        <DialogTitle>Bulk Update Status ({selectedIds.size} variant(s))</DialogTitle>
        <DialogContent sx={{ pt: "16px !important" }}>
          <FormLabel component="legend">Set variant status to:</FormLabel>
          <RadioGroup
            value={bulkStatus.isActive ? "active" : "inactive"}
            onChange={(e) => setBulkStatus({ isActive: e.target.value === "active" })}
          >
            <FormControlLabel value="active" control={<Radio size="small" />} label="Active (visible to customers)" />
            <FormControlLabel value="inactive" control={<Radio size="small" />} label="Inactive (hidden from customers)" />
          </RadioGroup>
        </DialogContent>
        <DialogActions>
          <Button onClick={() => setBulkStatusDialogOpen(false)} disabled={bulkLoading}>Cancel</Button>
          <Button
            variant="contained"
            color={bulkStatus.isActive ? "success" : "warning"}
            onClick={handleBulkStatusUpdate}
            disabled={bulkLoading}
            startIcon={bulkLoading ? <CircularProgress size={16} /> : undefined}
          >
            {bulkLoading ? "Updating..." : "Apply"}
          </Button>
        </DialogActions>
      </Dialog>

    </Box>
  );
};

export default VariantManager;
