export const createCouponDistributionEngine = ({
    couponAssignmentRepository,
    couponRepository,
    rulesService,
    userRepository,
    notificationService,
    createApiError,
}) =>
{
    const findOrCreateCoupon = async (trigger, couponConfig) =>
    {
        const existingCoupon = await couponRepository.findByTargetType(couponConfig.targetType);
        if (existingCoupon && existingCoupon.length > 0)
        {
            const validCoupon = existingCoupon.find((c) =>
                c.discountType === couponConfig.discountType &&
                c.isActive === true &&
                c.validityEndDate > new Date()
            );
            if (validCoupon) return validCoupon;
        }

        const now = new Date();
        const code = rulesService.generateCouponCode(trigger);
        const endDate = new Date(now.getTime() + (couponConfig.validityDays || 30) * 24 * 60 * 60 * 1000);

        const couponData = {
            code,
            name: `${trigger.replace(/_/g, ' ')} ${couponConfig.discountType === 'PERCENTAGE' ? couponConfig.discountValue + '% OFF' : '\u20B9' + couponConfig.discountValue + ' OFF'}`,
            description: `Auto-generated coupon for ${trigger}`,
            discountType: couponConfig.discountType,
            discountValue: couponConfig.discountType === 'PERCENTAGE' ? null : couponConfig.discountValue,
            discountPercentage: couponConfig.discountType === 'PERCENTAGE' ? couponConfig.discountValue : null,
            maximumDiscount: couponConfig.maximumDiscount || 0,
            validityStartDate: now,
            validityEndDate: endDate,
            minimumOrderValue: couponConfig.minimumOrderValue || 0,
            targetType: couponConfig.targetType,
            isActive: true,
            ownerType: 'PLATFORM',
            scope: 'ORDER',
            metadata: { autoGenerated: true, trigger },
        };

        return couponRepository.createCoupon(couponData);
    };

    const assignCoupon = async ({ userId, trigger, metadata = {} }) =>
    {
        const rule = rulesService.getRuleByTrigger(trigger);
        if (!rule) return null;

        if (rule.maxAssignmentsPerUser > 0)
        {
            const existingCount = await couponAssignmentRepository.countByUserAndStatus({
                userId,
                status: 'ASSIGNED',
            });
            if (existingCount >= rule.maxAssignmentsPerUser) return null;
        }

        const coupon = await findOrCreateCoupon(trigger, rule.couponConfig);

        const existingAssignment = await couponAssignmentRepository.findByUserAndCoupon({
            userId,
            couponId: coupon._id,
            trigger,
        });
        if (existingAssignment) return existingAssignment;

        const now = new Date();
        const assignmentData = {
            userId,
            couponId: coupon._id,
            trigger,
            assignedAt: now,
            expiresAt: new Date(now.getTime() + (rule.couponConfig.validityDays || 30) * 24 * 60 * 60 * 1000),
            status: 'ASSIGNED',
            metadata,
        };

        const assignment = await couponAssignmentRepository.create(assignmentData);

        try
        {
            await notificationService.send({
                recipientId: userId,
                type: 'COUPON_RECEIVED',
                title: 'Coupon Received!',
                body: `You've received a ${coupon.discountType === 'PERCENTAGE' ? coupon.discountPercentage + '%' : '\u20B9' + coupon.discountValue} discount coupon! Check your wallet.`,
                channels: ['IN_APP', 'EMAIL'],
                metadata: { couponId: coupon._id, assignmentId: assignment._id, trigger },
            });
        }
        catch (err)
        {
            // Notification failure should not break the assignment flow
        }

        return assignment;
    };

    const claimCoupon = async ({ userId, assignmentId }) =>
    {
        const assignment = await couponAssignmentRepository.claimAssignment({ id: assignmentId, userId });
        if (!assignment)
        {
            throw createApiError({
                statusCode: 404,
                code: 'ASSIGNMENT_NOT_FOUND',
                message: 'Coupon assignment not found or already claimed.',
            });
        }
        return assignment;
    };

    const getWallet = async (userId) =>
    {
        const assignments = await couponAssignmentRepository.findActiveByUser(userId);
        return assignments;
    };

    const expireAssignments = async () =>
    {
        return couponAssignmentRepository.expireAssignments();
    };

    const onUserRegistered = async (userId) =>
    {
        try
        {
            await assignCoupon({ userId, trigger: 'WELCOME_REGISTRATION' });
        }
        catch (err)
        {
            // Silently handle — registration flow must not break
        }
    };

    const onOrderCompleted = async ({ userId, order, isFirstOrder }) =>
    {
        try
        {
            if (isFirstOrder)
            {
                await assignCoupon({ userId, trigger: 'FIRST_PURCHASE' });
            }

            if (order.user && order.user.referredBy)
            {
                await assignCoupon({ userId: order.user.referredBy, trigger: 'REFERRAL' });
            }
        }
        catch (err)
        {
            // Silently handle — order flow must not break
        }
    };

    return Object.freeze({
        assignCoupon,
        claimCoupon,
        getWallet,
        expireAssignments,
        onUserRegistered,
        onOrderCompleted,
    });
};
