/**
 * Centralized notification system enums.
 * Object.freeze() prevents accidental mutation at runtime.
 */

export const NOTIFICATION_CHANNEL = Object.freeze({
  IN_APP: 'IN_APP',
  EMAIL: 'EMAIL',
  SMS: 'SMS',
  PUSH: 'PUSH',
});

export const NOTIFICATION_TYPE = Object.freeze({
  ORDER_PLACED: 'ORDER_PLACED',
  ORDER_CONFIRMED: 'ORDER_CONFIRMED',
  ORDER_SHIPPED: 'ORDER_SHIPPED',
  ORDER_DELIVERED: 'ORDER_DELIVERED',
  ORDER_CANCELLED: 'ORDER_CANCELLED',
  PAYMENT_RECEIVED: 'PAYMENT_RECEIVED',
  PAYMENT_FAILED: 'PAYMENT_FAILED',
  RETURN_REQUESTED: 'RETURN_REQUESTED',
  RETURN_APPROVED: 'RETURN_APPROVED',
  RETURN_REJECTED: 'RETURN_REJECTED',
  REFUND_PROCESSED: 'REFUND_PROCESSED',
  REFUND_FAILED: 'REFUND_FAILED',
  PAYOUT_PROCESSED: 'PAYOUT_PROCESSED',
  PAYOUT_FAILED: 'PAYOUT_FAILED',
  SELLER_VERIFICATION_APPROVED: 'SELLER_VERIFICATION_APPROVED',
  SELLER_VERIFICATION_REJECTED: 'SELLER_VERIFICATION_REJECTED',
  PRODUCT_APPROVED: 'PRODUCT_APPROVED',
  PRODUCT_REJECTED: 'PRODUCT_REJECTED',
  CATEGORY_REQUEST_APPROVED: 'CATEGORY_REQUEST_APPROVED',
  CATEGORY_REQUEST_REJECTED: 'CATEGORY_REQUEST_REJECTED',
  BRAND_REQUEST_APPROVED: 'BRAND_REQUEST_APPROVED',
  BRAND_REQUEST_REJECTED: 'BRAND_REQUEST_REJECTED',
  SYSTEM_ANNOUNCEMENT: 'SYSTEM_ANNOUNCEMENT',
  GENERIC: 'GENERIC',
});

export const NOTIFICATION_STATUS = Object.freeze({
  PENDING: 'PENDING',
  QUEUED: 'QUEUED',
  SENT: 'SENT',
  DELIVERED: 'DELIVERED',
  FAILED: 'FAILED',
  RETRYING: 'RETRYING',
});

export const NOTIFICATION_PRIORITY = Object.freeze({
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH',
  URGENT: 'URGENT',
});

export const NOTIFICATION_CATEGORY = Object.freeze({
  TRANSACTIONAL: 'TRANSACTIONAL',
  PROMOTIONAL: 'PROMOTIONAL',
  SYSTEM: 'SYSTEM',
  ALERT: 'ALERT',
});

export const NOTIFICATION_TYPE_VALUES = Object.freeze(
  Object.values(NOTIFICATION_TYPE)
);

export const NOTIFICATION_CHANNEL_VALUES = Object.freeze(
  Object.values(NOTIFICATION_CHANNEL)
);

export const NOTIFICATION_STATUS_VALUES = Object.freeze(
  Object.values(NOTIFICATION_STATUS)
);
